import http from 'node:http'
import fs from 'node:fs'
import path from 'node:path'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import { WebSocketServer } from 'ws'

const here=path.dirname(fileURLToPath(import.meta.url)),root=fs.existsSync(path.join(here,'dist'))?path.join(here,'dist'):here,rooms=new Map()
const ranks=[['A',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',11],['Q',12],['K',13]],suits=['♠','♥','♣','♦']
const points=h=>h.reduce((n,c)=>n+c.value,0),shuffle=a=>a.sort(()=>Math.random()-.5)
function deck(n){let id=0,a=[];for(let d=0;d<n;d++){suits.forEach(s=>ranks.forEach(([rank,value])=>a.push({id:`${d}-${id++}`,rank,value,suit:s})));a.push({id:`${d}-${id++}`,rank:'JOKER',value:0,suit:'★'},{id:`${d}-${id++}`,rank:'JOKER',value:0,suit:'★'})}return shuffle(a)}
function valid(cs){if(cs.length===1)return true;if(!cs.length)return false;let same=cs.every(c=>c.rank===cs[0].rank),unique=new Set(cs.map(c=>c.suit)).size===cs.length;if(cs.length===2)return same;if((cs.length===3||cs.length===4)&&same)return unique;if(cs.length>=3&&cs.length<=5&&cs.every(c=>c.suit===cs[0].suit)&&!cs.some(c=>c.rank==='JOKER')){let v=cs.map(c=>c.value).sort((a,b)=>a-b);return v.every((x,i)=>!i||x===v[i-1]+1)}return false}
const send=(ws,m)=>ws.readyState===1&&ws.send(JSON.stringify(m))
function view(room,id){let g=room.game,p=room.players.find(x=>x.id===id);return{code:room.code,hostId:room.hostId,config:room.config,players:room.players.map(x=>({id:x.id,name:x.name,seat:x.seat,host:x.host,score:x.score,eliminated:x.eliminated,cards:x.hand?.length||0,hand:g?.status==='results'?x.hand:undefined})),game:g?{status:g.status,turnId:g.turnId,phase:g.phase,round:g.round,offer:g.offer,deckCount:g.deck.length,declarerId:g.declarerId,message:g.message,results:g.results}:null,myHand:p?.hand||[]}}
function broadcast(room){room.sockets.forEach((ws,id)=>send(ws,{type:'room',room:view(room,id)}))}
function active(room){return room.players.filter(p=>!p.eliminated).sort((a,b)=>a.seat-b.seat)}
function startRound(room){let ps=active(room),d=deck(ps.length<=3?1:ps.length<=5?2:3);ps.forEach(p=>p.hand=d.splice(0,room.config.cards));room.game={status:'playing',turnId:ps[0].id,phase:'throw',round:1,offer:d.pop(),deck:d,declarerId:null,finalQueue:[],message:`${ps[0].name}'s turn`,results:null};broadcast(room)}
function nextTurn(room){let g=room.game,ps=active(room),current=ps.findIndex(p=>p.id===g.turnId);if(g.declarerId){if(!g.finalQueue.length)return finishRound(room);g.turnId=g.finalQueue.shift();g.phase='throw';g.message=`Final turn: ${room.players.find(p=>p.id===g.turnId).name}`;return broadcast(room)}let next=(current+1)%ps.length;if(next===0)g.round++;g.turnId=ps[next].id;g.phase='throw';g.message=`${ps[next].name}'s turn`;broadcast(room)}
function finishRound(room){let g=room.game,ps=active(room),dec=room.players.find(p=>p.id===g.declarerId),low=Math.min(...ps.filter(p=>p.id!==dec.id).map(p=>points(p.hand))),winner=points(dec.hand)<=low?dec:ps.find(p=>p.id!==dec.id&&points(p.hand)===low),total=ps.reduce((n,p)=>n+points(p.hand),0);ps.forEach(p=>{p.lastPoints=points(p.hand);p.roundScore=winner===dec?points(p.hand):p===winner?0:p===dec?total:points(p.hand);p.score+=p.roundScore;p.eliminated=p.score>=room.config.limit});let survivors=active(room);g.status='results';g.phase='ended';g.results={winnerId:winner.id,winnerName:winner.name,rows:ps.map(p=>({id:p.id,name:p.name,points:p.lastPoints,roundScore:p.roundScore,total:p.score,eliminated:p.eliminated,hand:p.hand})),gameWinner:survivors.length===1?survivors[0].name:null};g.message=`${winner.name} wins the round`;broadcast(room)}
function action(room,id,a){let g=room.game,p=room.players.find(x=>x.id===id);if(!g||g.status!=='playing'||g.turnId!==id)return;if(a.kind==='play'&&g.phase==='throw'){let chosen=p.hand.filter(c=>a.ids.includes(c.id));if(!valid(chosen))return;p.hand=p.hand.filter(c=>!a.ids.includes(c.id));g.phase='draw';g.message=`${p.name} played ${chosen.length} card${chosen.length>1?'s':''}`}
else if(a.kind==='draw'&&g.phase==='draw'){let c=a.source==='offer'?g.offer:g.deck.pop();if(!c)return;p.hand.push(c);if(a.source==='offer')g.offer=null;g.phase='postdraw';g.message=`${p.name} drew a card`}
else if(a.kind==='end'&&g.phase==='postdraw')return nextTurn(room)
else if(a.kind==='declare'&&g.phase==='postdraw'&&g.round>3){g.declarerId=id;g.finalQueue=active(room).filter(x=>x.id!==id).map(x=>x.id);g.message=`${p.name} declared with ${points(p.hand)} points`;return nextTurn(room)}broadcast(room)}

const server=http.createServer((req,res)=>{let rel=decodeURIComponent((req.url||'/').split('?')[0]).replace(/^\//,'')||'index.html',file=path.join(root,rel);fs.readFile(file,(e,data)=>{if(e)return fs.readFile(path.join(root,'index.html'),(x,f)=>{res.writeHead(x?404:200,{'Content-Type':'text/html'});res.end(x?'Not found':f)});let ext=path.extname(file),type={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'}[ext];res.writeHead(200,{'Content-Type':type||'application/octet-stream'});res.end(data)})})
const wss=new WebSocketServer({server,path:'/ws'})
wss.on('connection',ws=>{let code,id;ws.on('message',raw=>{let m;try{m=JSON.parse(raw)}catch{return}if(m.type==='create'){code=Math.random().toString(36).slice(2,8).toUpperCase();id=crypto.randomUUID();let room={code,hostId:id,config:m.config,players:[{id,name:m.name,seat:0,host:true,score:0,eliminated:false,hand:[]}],sockets:new Map([[id,ws]]),game:null};rooms.set(code,room);send(ws,{type:'identity',playerId:id});return broadcast(room)}if(m.type==='join'){let room=rooms.get(String(m.code).toUpperCase());if(!room)return send(ws,{type:'error',message:'Table not found'});code=room.code;id=crypto.randomUUID();room.sockets.set(id,ws);room.players.push({id,name:m.name,seat:null,host:false,score:0,eliminated:false,hand:[]});send(ws,{type:'identity',playerId:id});return broadcast(room)}let room=rooms.get(code);if(!room)return;if(m.type==='seat'&&!room.game){if(!room.players.some(p=>p.seat===m.seat&&p.id!==id))room.players.find(p=>p.id===id).seat=m.seat}else if(m.type==='config'&&id===room.hostId&&!room.game){room.config={...room.config,limit:m.limit}}else if(m.type==='start'&&id===room.hostId&&room.players.length>=2&&room.players.every(p=>p.seat!==null))startRound(room);else if(m.type==='next_round'&&id===room.hostId&&room.game?.status==='results'&&!room.game.results.gameWinner)startRound(room);else if(m.type==='action')action(room,id,m.action);broadcast(room)});ws.on('close',()=>{let room=rooms.get(code);if(!room)return;room.sockets.delete(id);if(!room.sockets.size)rooms.delete(code)})})
setInterval(()=>wss.clients.forEach(ws=>ws.readyState===1&&ws.ping()),25000)
server.listen(process.env.PORT||10000,'0.0.0.0')
